//
// Created by arman on 6/11/2020.
//

#ifndef CANTIDAD_ESTUDIANTES_ASIGNATURA_MI_LIBRERIA_H
#define CANTIDAD_ESTUDIANTES_ASIGNATURA_MI_LIBRERIA_H

#endif //CANTIDAD_ESTUDIANTES_ASIGNATURA_MI_LIBRERIA_H

//PARAMETRIZACION DE FUNCIONES
int imprimir_menu();
void ImprimirAprobados();